const defaultColor = 'dark:text-white text-gray-900';
const theme = {
  // These are the core Lexical theme properties that must be present
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder:
    'text-gray-400 overflow-hidden absolute text-ellipsis top-[8px] left-[10px] right-[10px] user-select-none pointer-events-none',
  paragraph: 'my-2 leading-normal',
  quote: 'border-l-4 border-gray-300 pl-4 my-2',
  heading: {
    h1: `text-2xl font-bold text-center my-4 ${defaultColor}`,
    h2: `text-xl font-semibold ${defaultColor}`,
    h3: `text-lg font-semibold ${defaultColor}`,
    h4: `text-base ${defaultColor}`,
    h5: `text-sm ${defaultColor}`,
    h6: `text-xs ${defaultColor}`,
  },
  list: {
    nested: {
      listitem: 'ml-5',
    },
    ol: 'list-decimal pl-5 my-2',
    ul: 'list-disc pl-5 my-2',
    listitem: 'ml-1 leading-normal',
    listitemChecked: 'line-through',
    listitemUnchecked: '',
  },
  image: 'max-w-full h-auto',
  link: 'text-blue-600 underline cursor-pointer hover:text-blue-800',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-gray-100 p-1 rounded font-mono text-sm',
  },
  code: 'bg-gray-100 p-4 rounded font-mono text-sm block whitespace-pre-wrap',
  codeHighlight: {
    atrule: 'text-blue-600',
    attr: 'text-purple-600',
    boolean: 'text-red-600',
    builtin: 'text-yellow-600',
    cdata: 'text-gray-500',
    char: 'text-green-600',
    class: 'text-blue-600',
    'class-name': 'text-blue-600',
    comment: 'text-gray-500 italic',
    constant: 'text-orange-600',
    deleted: 'text-red-600',
    doctype: 'text-gray-500',
    entity: 'text-yellow-600',
    function: 'text-blue-600',
    important: 'text-purple-600 font-bold',
    inserted: 'text-green-600',
    keyword: 'text-purple-600',
    namespace: 'text-yellow-600',
    number: 'text-orange-600',
    operator: 'text-yellow-600',
    prolog: 'text-gray-500',
    property: 'text-red-600',
    punctuation: 'text-gray-700',
    regex: 'text-red-600',
    selector: 'text-green-600',
    string: 'text-green-600',
    symbol: 'text-orange-600',
    tag: 'text-red-600',
    url: 'text-blue-600',
    variable: 'text-purple-600',
  },
};

export default theme;
